# Generated by Django 4.1 on 2024-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfoModel",
            fields=[
                (
                    "code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("company", models.CharField(max_length=40)),
                ("market_type", models.CharField(max_length=20)),
                ("last_update", models.DateField()),
            ],
            options={
                "db_table": "company_info",
            },
        ),
        migrations.CreateModel(
            name="DailyPriceModel",
            fields=[
                (
                    "code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("open", models.BigIntegerField()),
                ("high", models.BigIntegerField()),
                ("low", models.BigIntegerField()),
                ("close", models.BigIntegerField()),
                ("diff", models.BigIntegerField()),
                ("volume", models.BigIntegerField()),
            ],
            options={
                "db_table": "daily_price",
                "unique_together": {("code", "date")},
            },
        ),
    ]
