# Generated by Django 5.0.3 on 2024-03-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedRulesModel',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('rules', models.TextField()),
            ],
            options={
                'db_table': 'matched_rules',
            },
        ),
    ]
