# Generated by Django 4.1 on 2024-02-11 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mongoDBApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MatchedRulesModel",
        ),
    ]
